### ISSUE TITLE
How are you defining "new tab" for this extension?

### ISSUE THREAD

**Issue by Gitoffthelawn** [Nidre/firefox-open-tabs-next-to-current-plus#5] opened 2015-09-17 02:20 UTC
The description of the extension states: "Opens all new tabs always next to the current tab except when a new tab is created either by new tab button or hotkey".

Is it supposed to affect all tabs that are opened from links in existing tabs or only "new tabs" (those that are typically created by pressing the new tab button or hotkey, also known as about:newtab)?

The extension affects all tabs... not sure if this is by design or an error.  I'm starting to think it is by design, and I misunderstood the use of "new tab" in the description to be equivalent to "about:newtab" (which is what I actually want)!

If it's by design, would be interested in writing a small extension that just creates new tabs to the right of the current tab when Ctrl+T is pressed?

**Comment by Ludomancer** [comment] 2015-09-22 22:33
The addon does the following;
- If you open a new tab by clicking new tab button on Firefox tab bar, it will open the tab as how would Firefox do by default.
-  If you open a new tab by using defined shortcut in options page of this addon(Ctrl + Alt + Shift + T by default), it will again open the tab as how would Firefox do by default.
- If you open a new tab by any other way (middle-click, Ctrl + T, etc...), it will open the new tab next to the current tab.

So probably answer to your question is yes, it is by design. I will note that idea of yours, but can't promise anything since I currently have a very busy schedule. Let me know if that answers your question, if so I will close this ticket.

Thanks for taking the time to write!

@Gitoffthelawn

**Comment by Gitoffthelawn** [comment] 2015-09-23 01:58
Thanks for the details.

To clarify, every time you used "new tab" in your response, you are referring to the _about:newtab_ page, correct?

If you will, let me know.

If so, I think there is a bug or a conflict.  The extension seems to affect all tabs, not just _about:newtab_ tabs.  Since you are busy, let's leave this open for now until we both have time to work on it.  But if you let me know the answer to the above question, that will help!

**Comment by Ludomancer** [comment] 2015-09-23 09:06
@Gitoffthelawn 
Extension affects whenever you open new tab. It doesn't matter which URL it has. There is no distinction made if it is about:newtab or not. It is by design.

**Comment by Gitoffthelawn** [comment] 2015-09-23 10:16
Thanks.  I think we are conveying the same thing, but using different words.  ;)

When you right-click on a link and select 'Open Link in New Tab', is the extension supposed to consider that a new tab?

**Comment by Ludomancer** [comment] 2015-09-23 10:35
Yes. Any kind of new tab is considered a new tab.

**Comment by Gitoffthelawn** [comment] 2015-09-24 05:58
Thanks.  That explains quite a bit!

It's not what I want, but that's okay... it's your extension and works well for your design... and I have total respect for that.

What I was looking for was an extension that only applied the functionality to 'new tabs', using the other definition of new tabs: tabs that Firefox classifies as _about:newtab_.  IOW, when I right -click on a link and select 'Open Link in New Tab', I don't want it to apply, because that's not an _about:newtab_.  However, if I press Ctrl+T, I want it to apply because that's an _about:newtab_.

The term 'new tab' is ambiguous, as it is used to mean two different things.  In the case of your extension, I thought that term was using one definition, but it was using the other.

If you add an option to accommodate this use, that would be great, but since the extension is working as it was designed, I understand completely if you choose not to add this option.

If you don't add such an option, you may consider clarifying the AMO description by indicating that the functionality applies to every tab that is opened.

Either way, it's a well-written extension!  :-)

**Comment by Ludomancer** [comment] 2015-09-24 10:59
Glad it is clear now :) I will consider this feature, thanks for bringing it up!

**Closed as completed by Ludomancer** 2015-09-24 10:59 UTC

**Comment by Gitoffthelawn** [comment] 2015-09-24 17:00
You're welcome... and thank _you_.   :-)
